### ISSUE TITLE
Links to stylesheets don't work on pages with folders

### ISSUE THREAD

**Issue by dfranklinau** [phocks/phocks.github.io#12]
The links to stylesheets are relative, which means they do not load correctly on pages with folders, such as the below link:
http://phocks.github.io/page2/

One way of fixing this is to insert a `/` before the stylesheet URLs in the `_layouts/head.html` template, like so:

```
<link rel="stylesheet" href="/{{ site.baseurl }}public/css/poole.css">
<link rel="stylesheet" href="/{{ site.baseurl }}public/css/syntax.css">
<link rel="stylesheet" href="/{{ site.baseurl }}public/css/lanyon.css">
```

I'm unable to confirm if this _will_ fix the issue on my machine as I am unsure of the build commands, etc., but I will submit a pull request with the patch for you to check.

**Comment by phocks** [comment]
Thanks this seemed to work, but now there's another issue with pagination going /page2/page3 instead of just /page3

I think maybe GitHub's underlying Jekyll install changed or something because pagination definitely used to work perfectly.

**Comment by phocks** [comment]
OK I've just updated my code to match the code in Lanyon theme. Looks like they've fixed this issue over there a while ago and I was still on an old version. Cheers for bringing up this issue. All good now I think!

**Comment by dfranklinau** [comment]
Ah, that's great. Apologies for the band-aid fix! I'm glad you found the underlying cause by updating the theme.

I have noticed that the links to posts now have a `//` in front of them, which is making the browser link to an entirely new domain by mistake. I think this is because of the [change in this commit](https://github.com/phocks/phocks.github.io/commit/155ecedd3c003df51509b59e8c3032ba6ab3ba01).

If you change Line 10 from:

```
<a href="{{ site.baseurl }}/{{ post.url }}">
```

...to...

```
<a href="{{ post.url }}">
```

...that should resolve the issue, based on the documentation from [Jekyll's site for `page` variables](https://jekyllrb.com/docs/variables/#page-variables) which says that the output of `post.url` will be formatted as `/2008/12/14/my-post.html`, where the URL has a leading slash.

Sorry for inadvertently causing another issue! 😬

**Comment by phocks** [comment]
Ahhhh, great. This is fixed now too :)
